Repository everyone-s-garden/front-v2, pull requests merged in 2024-11, with the labels that each got.

#131 feat: 유저의 소리함 글자수 제한 문구 추가
  src/pages/MyPage/components/UserFeedbackModal.tsx
Labels: :sparkles: feat

#135 feat: 채팅방 나가기 연결
  src/pages/Chat/ChatContent/ChatContents.tsx
  src/pages/Chat/ChatContent/components/BtnItems.tsx
  src/pages/Chat/ChatContent/components/ContentHeader.tsx
  src/services/chat/api.ts
  src/services/chat/query.ts
Labels: :sparkles: feat

#136 fix: 지도 상세페이지에서 뒤로가기시 헤더 사라지는 문제 해결
  src/components/Header/MobileHeader.tsx
Labels: :bug: fix

#137 텃밭 일기 필드 수정
  src/components/ImageSelector/ImageSelector.tsx
  src/components/ImageSelector/constants.ts
  src/pages/Garden/MyGardenEdit/MyGardenEdit.tsx
  src/pages/Garden/MyGardenEdit/schema.ts
  src/pages/Garden/components/SearchBar.tsx
Labels: :sparkles: feat, :lipstick: style

#139 fix: 지도 페이지 텃밭 리스트에서 하나의 텃밭 클릭 시 텃밭 상세보기가 보이지 않는 문제 해결
  src/pages/Main/components/RecentPosts/RecentPostItem.tsx
  src/pages/Map/components/GardensContainer.tsx
  src/pages/Map/components/MapAside/MapAside.tsx
  src/pages/Map/components/MapAside/components/GardenDetail/GardenDetail.tsx
  src/pages/Map/components/MapAside/components/GardenList/GardenList.tsx
  src/pages/Map/components/MapComponent.tsx
Labels: :bug: fix

#145 130 qa 마이페이지 텃밭 일기 수정하기 및 삭제하기 api 연동
  src/components/DatePicker/DatePicker.tsx
  src/components/ImageSelector/ImageSelector.tsx
  src/pages/Community/CommunityEdit/CommunityEdit.tsx
  src/pages/Garden/GardenEdit/GardenEdit.tsx
  src/pages/Garden/MyGardenEdit/MyGardenEdit.tsx
  src/pages/Garden/components/AddressSearchBar.tsx
  src/pages/MyPage/NearByGardensInfo/GardenDiary/GardenDiary.tsx
  src/pages/MyPage/NearByGardensInfo/MyPost/MyPost.tsx
  src/pages/MyPage/components/GardenItem.tsx
  src/pages/MyPage/components/MenuButton.tsx
  src/pages/MyPage/components/UserFeedbackModal.tsx
  src/pages/Profile/components/ProfileGarden/ProfileGarendFooter.tsx
  src/services/garden/api.ts
  src/services/garden/query.ts
  src/services/mypage/api.ts
  src/services/mypage/query.ts
  src/stores/imageStore.ts
Labels: :sparkles: feat, :lipstick: style

#146 분양 텃밭 등록하기 버그 수정 및 마이페이지 api 등록 및 버그 수정
  .storybook/preview.tsx
  src/components/ImageSelector/ImageSelector.tsx
  src/pages/Garden/GardenEdit/GardenEdit.tsx
  src/pages/Garden/MyGardenEdit/MyGardenEdit.tsx
  src/pages/Garden/components/AddressSearchBar.tsx
  src/pages/MyPage/NearByGardensInfo/FavoritedGardens/FavoritedGardens.tsx
  src/pages/MyPage/NearByGardensInfo/MyPost/MyPost.tsx
  src/pages/MyPage/components/GardenItem.tsx
  src/pages/MyPage/components/UserProfile.tsx
  src/services/gardens/api.ts
  src/services/gardens/mutations.ts
Labels: :sparkles: feat, :bug: fix
