Repository everyone-s-garden/front-v2, pull requests merged in 2024-06, with the labels that each got.

#76 fix: errorboudary 적용 및 작물 이미지 src 해결
  package-lock.json
  package.json
  src/pages/Main/components/MonthlyCrop.tsx
  src/pages/Main/components/Weather/Weather.tsx
  src/pages/Main/utils/getMonthImage.ts
Labels: :bug: fix

#77 신고하기 페이지 분리
  src/api/apiClient.ts
  src/pages/Community/CommunityDetail/components/Comment.tsx
  src/pages/Community/CommunityDetail/components/Content.tsx
  src/pages/Map/MapReport/components/MapReportCategory.tsx
  src/pages/Map/MapReport/components/MapReportCategoryDropdown.tsx
  src/pages/Map/MapReport/components/MapReportContents.tsx
  src/pages/Map/MapReport/components/MapReportForm.tsx
  src/pages/Map/MapReport/components/MobileReportBottomMenu.tsx
  src/pages/Map/MapReport/components/categoryArr.ts
  src/pages/Map/components/MapGardenDetailBottomSection.tsx
  src/pages/Report/Report.tsx
  src/pages/Report/components/ReportCategory.tsx
  src/pages/Report/components/ReportContents.tsx
  src/pages/Report/components/ReportForm.tsx
  src/pages/Report/components/ReportNotice.tsx
  src/pages/Report/constants.ts
  src/pages/Report/schema.ts
  src/pages/Report/types.ts
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/report/api.ts
  src/services/report/mutation.ts
  src/services/report/report.d.ts
  src/services/report/types.ts
  src/styles/globalStyles.ts
  src/types/error.ts
Labels: :sparkles: feat

#80 속닥속닥 리팩토링 (2)
  src/assets/icons/comments.svg
  src/assets/icons/index.ts
  src/assets/icons/paragraph-box.svg
  src/assets/icons/post-box.svg
  src/assets/images/grade/farmer.png
  src/assets/images/grade/fruit.png
  src/assets/images/grade/harvest.png
  src/assets/images/grade/seed.png
  src/assets/images/grade/sprout.png
  src/assets/images/grade/stem.png
  src/assets/images/index.ts
  src/components/Empty/Empty.stories.tsx
  src/components/Empty/Empty.tsx
  src/components/Empty/constants.ts
  src/components/Grade/Grade.stories.tsx
  src/components/Grade/Grade.tsx
  src/components/Modal/BlockerModal.tsx
  src/components/PostList/PostList.tsx
  src/data/dummyData.ts
  src/pages/Community/CommunityDetail/CommunityDetail.tsx
  src/pages/Community/CommunityDetail/components/AuthorInfo.tsx
  src/pages/Community/CommunityDetail/components/CommentSection.tsx
  src/pages/Community/CommunityEdit/CommunityEdit.tsx
  src/pages/Community/CommunityEdit/components/SubmitButton.tsx
  src/pages/Community/CommunityMain/CommunityMain.tsx
  src/pages/Community/types.ts
  src/pages/Garden/GardenEdit/GardenEdit.tsx
  src/pages/Garden/MyGardenEdit/MyGardenEdit.tsx
  src/types/grade.ts
Labels: :recycle: refactor

#85 이미지 슬라이더 컴포넌트 스타일 수정
  src/components/ImageSlider/ImageSlider.tsx
Labels: :lipstick: style

#86 작성 페이지 리팩토링
  package-lock.json
  package.json
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/DatePickerCalendar.tsx
  src/pages/Garden/GardenEdit/GardenEdit.tsx
  src/pages/Garden/GardenEdit/schema.ts
  src/pages/Garden/components/Input.tsx
  src/routes/router.tsx
  src/utils/removeNumberFormatting.ts
Labels: :recycle: refactor

#87 메인페이지 추가 수정 작업
  src/assets/icons/weather/index.ts
  src/assets/icons/weather/mainMostlyCloudy-icon.svg
  src/assets/icons/weather/mainSunny-icon.svg
  src/assets/images/default_post.png
  src/assets/images/index.ts
  src/pages/Main/components/RecentPosts/RecentPostItem.tsx
  src/pages/Main/components/RecentPosts/RecentPosts.tsx
  src/pages/Main/components/RecentPosts/swiperNavigationArrow.css
  src/pages/Main/components/Weather/CurrentWeather.tsx
  src/pages/Main/components/Weather/HourlyWeather.tsx
  src/pages/Main/components/Weather/WeeklyWeather.tsx
  src/pages/Main/utils/getBackgroundColorFromWeather.ts
  src/pages/Main/utils/getWeatherIcon.ts
  src/pages/Map/components/MapComponent.tsx
Labels: :sparkles: feat, :bug: fix, :lipstick: style

#88 속닥속닥 리팩토링 (3)
  package-lock.json
  package.json
  src/components/AlertToast/AlertToast.tsx
  src/components/Grade/Grade.tsx
  src/components/Header/Header.tsx
  src/components/Header/PostMenu.tsx
  src/components/PostList/PostList.tsx
  src/components/index.ts
  src/hooks/useClipboard.ts
  src/pages/Community/CommunityDetail/CommunityDetail.tsx
  src/pages/Community/CommunityDetail/components/AuthorInfo.tsx
  src/pages/Community/CommunityDetail/components/Comment.tsx
  src/pages/Community/CommunityDetail/components/Content.tsx
  src/pages/Community/CommunityDetail/components/Interaction.tsx
  src/pages/Community/CommunityDetail/components/contentStyles.ts
  src/pages/Community/CommunityEdit/CommunityEdit.tsx
  src/pages/Community/CommunityEdit/components/MobileHeader.tsx
  src/pages/Community/CommunityEdit/components/SubmitButton.tsx
  src/pages/Community/CommunityEdit/components/ToolBar.tsx
  src/pages/Community/CommunityEdit/components/editorStyles.ts
  src/pages/Community/CommunityMain/CommunityMain.tsx
  src/pages/Map/components/MapGardenDetailBottomSection.tsx
  src/routes/HiddenHeaderLayout.tsx
  src/routes/router.tsx
  src/styles/globalStyles.ts
Labels: :recycle: refactor

#92 채팅 페이지 기능 추가 및 디자인 수정
  src/components/Avatar/Avatar.tsx
  src/pages/Chat/ChatContent/components/ChatBubble.tsx
  src/pages/Chat/ChatContent/components/ContentHeader.tsx
  src/pages/Chat/ChatList/ChatListItem.tsx
  src/services/chat/type.ts
  src/services/gardens/api.ts
Labels: :sparkles: feat, :lipstick: style
