Repository everyone-s-garden/front-v2, pull requests merged in 2024-03, with the labels that each got.

#10 드롭다운 컴포넌트 구현
  .eslintrc.cjs
  .github/workflows/chromatic.yml
  package-lock.json
  package.json
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Header/Header.stories.ts
  src/components/Header/Header.tsx
  src/components/ImageSelector/ImageSelector.tsx
  src/components/index.ts
  src/pages/Chat/Chat.tsx
  src/pages/Community/CommunityDetail/CommunityDetail.tsx
  src/pages/Community/CommunityMain/CommunityMain.tsx
  src/pages/Create/CommunityEdit/CommunityEdit.tsx
  src/pages/Create/GardenEdit/GardenEdit.tsx
  src/pages/Create/MyGardenEdit/MyGardenEdit.tsx
  src/pages/Example/Example.tsx
  src/pages/Login/Login.tsx
  src/pages/Main/Main.tsx
  src/pages/Map/Map.tsx
  src/pages/My/My.tsx
  src/pages/index.ts
  src/routes/Layout.tsx
  src/routes/router.tsx
  src/styles/components/button.ts
  src/styles/components/menu.ts
  src/styles/theme.ts
Labels: :sparkles: feat

#26 모달 컴포넌트 구현
  src/assets/icons/index.ts
  src/assets/icons/location-icon.svg
  src/assets/icons/modal-plus-button.svg
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
  src/components/index.ts
Labels: :sparkles: feat

#11 이미지 슬라이더 컴포넌트 구현
  src/assets/images/banners/banner1.png
  src/assets/images/banners/banner2.png
  src/assets/images/index.ts
  src/components/ImageSlider/Arrow.tsx
  src/components/ImageSlider/ImageSlider.stories.tsx
  src/components/ImageSlider/ImageSlider.tsx
  src/components/index.ts
Labels: :sparkles: feat

#24 모바일 메뉴 컴포넌트 구현
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/BottomMenu/BottomMenu.stories.tsx
  src/components/BottomMenu/BottomMenu.tsx
  src/components/index.ts
  src/styles/components/button.ts
Labels: :sparkles: feat

#20 탭 컴포넌트 구현
  src/components/Header/Header.tsx
  src/components/Header/NavTab.tsx
  src/components/Header/constants.ts
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.tsx
  src/components/Tab/types.ts
  src/components/index.ts
  src/styles/components/tab.ts
  src/styles/theme.ts
Labels: :sparkles: feat

#18 달력 컴포넌트 구현
  .gitignore
  src/assets/icons/arrow-down.svg
  src/assets/icons/index.ts
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/DatePickerCalendar.tsx
Labels: :sparkles: feat

#19 태그 컴포넌트 구현
  .gitignore
  src/components/Tag/Tag.stories.tsx
  src/components/Tag/index.tsx
  src/components/index.ts
  src/pages/Main/Main.tsx
  src/routes/Layout.tsx
  src/styles/components/tag.ts
  src/styles/theme.ts
Labels: :sparkles: feat

#22 아바타 컴포넌트 구현
  .gitignore
  src/assets/icons/default-profile.svg
  src/assets/icons/index.ts
  src/components/Avatar/Avatar.stories.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Header/Header.tsx
  src/components/ImageSlider/ImageSlider.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Tag/Tag.stories.tsx
  src/components/Tag/Tag.tsx
  src/components/index.ts
Labels: :sparkles: feat

#29 이미지 캐러셀 버그 해결
  package-lock.json
  package.json
  src/assets/icons/close.svg
  src/components/ImageSelector/Arrow.tsx
  src/components/ImageSelector/ImageSelector.stories.tsx
  src/components/ImageSelector/ImageSelector.tsx
  src/components/ImageSelector/constants.ts
Labels: :bug: fix

#31 코드 스니펫, 스토리북 작업
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  .vscode/settings.json
  .vscode/snippet.code-snippets
  .vscode/tasks.json
  README.md
  package-lock.json
  package.json
  src/components/DatePicker/DatePicker.stories.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Header/Header.stories.ts
  src/components/Header/Header.tsx
  src/components/ImageSlider/ImageSlider.stories.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Tab/Tab.stories.tsx
  src/components/Tab/Tab.tsx
Labels: :hammer: chore

#34 속닥속닥 페이지 마크업
  .vscode/snippet.code-snippets
  src/assets/icons/comment.svg
  src/assets/icons/heart.svg
  src/assets/icons/index.ts
  src/assets/icons/search.svg
  src/assets/icons/share.svg
  src/components/Avatar/Avatar.tsx
  src/components/Header/Header.tsx
  src/components/PostList/PostList.stories.tsx
  src/components/PostList/PostList.tsx
  src/components/index.ts
  src/data/dummyData.ts
  src/pages/Community/CommunityEdit/CommunityEdit.tsx
  src/pages/Community/CommunityMain/CommunityMain.tsx
  src/pages/Community/CommunityMain/components/CommunityHeader.tsx
  src/pages/Community/CommunityMain/components/Order.tsx
  src/pages/Community/CommunityMain/components/PostType.tsx
  src/pages/Community/CommunityMain/components/Search.tsx
  src/pages/Community/constants.ts
  src/pages/Community/types.ts
  src/pages/Create/GardenEdit/GardenEdit.tsx
  src/pages/Garden/GardenEdit/GardenEdit.tsx
  src/pages/Garden/MyGardenEdit/MyGardenEdit.tsx
  src/pages/index.ts
  src/routes/Layout.tsx
  src/routes/router.tsx
  src/styles/components/tab.ts
  src/styles/theme.ts
  tsconfig.json
Labels: :sparkles: feat, :lipstick: style
