Repository everyone-s-garden/front-v2, pull requests merged in 2024-09, with the labels that each got.

#103 속닥속닥 에디터 라이브러리 변경
  package-lock.json
  package.json
  src/components/ImageSelector/ImageSelector.tsx
  src/pages/Community/CommunityDetail/components/contentStyles.ts
  src/pages/Community/CommunityEdit/CommunityEdit.tsx
  src/pages/Community/CommunityEdit/components/Editor.tsx
  src/pages/Community/CommunityEdit/components/ToolBar.tsx
  src/pages/Community/CommunityEdit/components/editorStyles.ts
  src/pages/Community/CommunityEdit/editorExtensions.ts
  src/pages/Community/CommunityEdit/editorStyles.ts
  src/pages/Community/CommunityEdit/hooks/useBlockTool.ts
  src/pages/Community/CommunityEdit/hooks/useInlineTool.ts
  src/pages/Community/CommunityEdit/schema.ts
Labels: :bug: fix, :recycle: refactor

#105 디자인 및 컬러 변경에 따른 css 변경 작업
  index.html
  package-lock.json
  package.json
  src/pages/Map/components/MapAside/components/GardenDetail/MobileMapSlider.tsx
  src/styles/globalStyles.ts
  src/styles/theme.ts
Labels: :lipstick: style, :hammer: chore

#107 header 컴포넌트 수정
  src/components/Header/Header.tsx
  src/components/Header/MobileHeader.tsx
  src/components/Header/PcHeader.tsx
  src/components/Header/PostMenu.tsx
  src/components/Header/constants.ts
  src/components/Header/mainLogo.svg
  src/routes/HiddenHeaderLayout.tsx
  src/routes/Layout.tsx
Labels: :sparkles: feat, :lipstick: style, :recycle: refactor

#110 유저의 소리함 fab 버튼 스타일 및 레이아웃 리팩토링
  src/assets/icons/index.ts
  src/assets/icons/user-feedback-fab.svg
  src/assets/images/fab/pc_fab.png
  src/assets/images/index.ts
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Header/PostMenu.tsx
  src/components/Header/constants.ts
  src/components/UserFeedbackFab/UserFeedbackFab.tsx
  src/components/UserFeedbackFab/constants.ts
  src/constants/postOptions.ts
  src/pages/Community/CommunityEdit/utils/BlockUtils.ts
  src/pages/Community/CommunityEdit/utils/InlineUtils.ts
  src/pages/Community/CommunityEdit/utils/isEditorEmpty.ts
  src/pages/Community/CommunityMain/CommunityMain.tsx
  src/routes/Layout.tsx
Labels: :lipstick: style, :recycle: refactor

#113 fix: 속닥속닥 댓글 엔터키 입력 방지
  src/pages/Community/CommunityDetail/components/CommentInput.tsx
Labels: :bug: fix

#115 채팅 페이지 리팩토링 및 모바일 버그 해결
  src/pages/Chat/Chat.tsx
  src/pages/Chat/ChatContent/ChatContents.tsx
  src/pages/Chat/ChatContent/StartContent.tsx
  src/pages/Chat/ChatContent/components/BtnItems.tsx
  src/pages/Chat/ChatContent/components/ChatBubble.tsx
  src/pages/Chat/ChatContent/components/ContentChatList.tsx
  src/pages/Chat/ChatContent/components/ContentHeader.tsx
  src/pages/Chat/ChatContent/components/ContentInput.tsx
  src/pages/Chat/ChatContent/components/MobileHeader.tsx
  src/pages/Chat/ChatList/ChatList.tsx
  src/pages/Chat/ChatList/ChatListItem.tsx
Labels: :lipstick: style, :recycle: refactor
