Repository everyone-s-garden/front-v2, pull requests merged in 2024-05, with the labels that each got.

#42 속닥속닥 게시글 페이지 마크업
  .storybook/main.ts
  package-lock.json
  package.json
  src/assets/icons/comment-plus.svg
  src/assets/icons/index.ts
  src/components/PostList/PostList.tsx
  src/data/dummyData.ts
  src/pages/Community/CommunityDetail/CommunityDetail.tsx
  src/pages/Community/CommunityDetail/components/AuthorInfo.tsx
  src/pages/Community/CommunityDetail/components/Comment.tsx
  src/pages/Community/CommunityDetail/components/CommentInput.tsx
  src/pages/Community/CommunityDetail/components/CommentOrder.tsx
  src/pages/Community/CommunityDetail/components/CommentSection.tsx
  src/pages/Community/CommunityDetail/components/Content.tsx
  src/pages/Community/CommunityDetail/components/Interaction.tsx
  src/pages/Community/constants.ts
  src/pages/Community/types.ts
  src/styles/components/tag.ts
  src/styles/globalStyles.ts
Labels: :sparkles: feat, :lipstick: style

#54 소셜 로그인
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiClient.ts
  src/assets/icons/index.ts
  src/assets/icons/kakao-logo.svg
  src/components/Header/Header.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/components/LoginLink.tsx
  src/pages/Redirection/KakaoRedirection.tsx
  src/pages/Redirection/NaverRedirection.tsx
  src/routes/constants.ts
  src/routes/router.tsx
  src/services/login/api.ts
  src/services/login/login.d.ts
  src/services/login/tokenManager.ts
  src/stores/useLoginStore.ts
  src/utils/session.ts
  vite.config.ts
Labels: :sparkles: feat

#52 속닥속닥 게시글 페이지 기능
  .gitignore
  .storybook/preview.tsx
  src/assets/icons/index.ts
  src/assets/icons/paragraph.svg
  src/assets/icons/post.svg
  src/components/Empty/Empty.stories.tsx
  src/components/Empty/Empty.tsx
  src/components/Empty/constants.ts
  src/data/dummyData.ts
  src/pages/Community/CommunityDetail/CommunityDetail.tsx
  src/pages/Community/CommunityDetail/components/Comment.tsx
  src/pages/Community/CommunityDetail/components/CommentInput.tsx
  src/pages/Community/CommunityDetail/components/CommentOrder.tsx
  src/pages/Community/CommunityDetail/components/CommentSection.tsx
  src/pages/Community/CommunityDetail/components/Content.tsx
  src/pages/Community/CommunityDetail/components/Interaction.tsx
  src/pages/Community/CommunityMain/CommunityMain.tsx
  src/pages/Community/types.ts
  src/services/whisper/api.ts
  src/services/whisper/query.ts
  src/stores/whisperStore.ts
  vercel.json
  vite.config.ts
Labels: :sparkles: feat

#53 속닥속닥 작성 페이지 기능
  package-lock.json
  package.json
  src/components/ImageSelector/ImageSelector.tsx
  src/pages/Community/CommunityEdit/CommunityEdit.tsx
  src/pages/Community/CommunityEdit/components/Editor.tsx
  src/pages/Community/CommunityEdit/components/SubmitButton.tsx
  src/pages/Community/CommunityEdit/components/ToolBar.tsx
  src/pages/Community/CommunityEdit/components/editorStyles.ts
  src/pages/Community/CommunityEdit/components/toolData.ts
  src/pages/Community/CommunityEdit/constants.ts
  src/pages/Community/CommunityEdit/constants.tsx
  src/pages/Community/CommunityEdit/schema.ts
  src/pages/Community/CommunityEdit/types.ts
  src/pages/Community/CommunityEdit/utils/BlockUtils.ts
  src/pages/Community/CommunityEdit/utils/InlineUtils.ts
  src/pages/Community/CommunityEdit/utils/isEditorEmpty.ts
  src/services/whisper/api.ts
  src/services/whisper/query.ts
  src/stores/imageStore.ts
  src/styles/components/menu.ts
  src/styles/globalStyles.ts
  vite.config.ts
Labels: :sparkles: feat

#57 소셜 로그인
  src/App.tsx
  src/assets/icons/index.ts
  src/assets/icons/login-logo.svg
  src/pages/Login/Login.tsx
  src/pages/Redirection/Redirection.tsx
  src/routes/router.tsx
  vite.config.ts
Labels: :sparkles: feat

#47 채팅 페이지 마크업
  src/assets/icons/default-profile.svg
  src/assets/icons/etc.svg
  src/assets/icons/index.ts
  src/assets/images/default_profile.png
  src/assets/images/index.ts
  src/components/Avatar/Avatar.tsx
  src/pages/Chat/Chat.tsx
  src/pages/Chat/ChatContent/ChatContent.tsx
  src/pages/Chat/ChatContent/StartContent.tsx
  src/pages/Chat/ChatContent/components/BtnItems.tsx
  src/pages/Chat/ChatContent/components/ChatBubble.tsx
  src/pages/Chat/ChatContent/components/ContentChatList.tsx
  src/pages/Chat/ChatContent/components/ContentHeader.tsx
  src/pages/Chat/ChatContent/components/ContentInput.tsx
  src/pages/Chat/ChatContent/components/MobileHeader.tsx
  src/pages/Chat/ChatList/ChatList.tsx
  src/pages/Chat/ChatList/ChatListItem.tsx
  src/pages/index.ts
  src/routes/constants.ts
  src/routes/router.tsx
Labels: :sparkles: feat, :lipstick: style

#60 속닥속닥 리팩토링
  src/api/apiClient.ts
  src/pages/Community/CommunityDetail/CommunityDetail.tsx
  src/pages/Community/CommunityDetail/components/AuthorInfo.tsx
  src/pages/Community/CommunityDetail/components/Comment.tsx
  src/pages/Community/CommunityDetail/components/CommentInput.tsx
  src/pages/Community/CommunityDetail/components/CommentSection.tsx
  src/pages/Community/CommunityDetail/components/Content.tsx
  src/pages/Community/CommunityDetail/components/Interaction.tsx
  src/pages/Community/CommunityEdit/CommunityEdit.tsx
  src/services/whisper/api.ts
  src/services/whisper/query.ts
Labels: :recycle: refactor

#63 소셜 로그인
  src/App.tsx
  src/api/apiClient.ts
  src/components/Header/Header.tsx
  src/pages/Redirection/KakaoRedirection.tsx
  src/pages/Redirection/NaverRedirection.tsx
  src/pages/Redirection/Redirection.tsx
  src/services/login/api.ts
Labels: :sparkles: feat

#64 헤더 컴포넌트 기능
  src/assets/icons/heart.svg
  src/assets/icons/profile.svg
  src/components/Header/Header.stories.ts
  src/components/Header/Header.tsx
  src/components/Header/PostMenu.tsx
  src/routes/AuthRoute.tsx
  src/routes/GuestRoute.tsx
  src/routes/HiddenHeaderLayout.tsx
  src/routes/Layout.tsx
  src/routes/router.tsx
Labels: :sparkles: feat

#67 채팅 페이지 기능 추가
  package.json
  src/pages/Chat/ChatContent/ChatContent.tsx
  src/pages/Chat/ChatContent/ChatContents.tsx
  src/pages/Chat/ChatContent/StartContent.tsx
  src/pages/Chat/ChatContent/components/ChatBubble.tsx
  src/pages/Chat/ChatContent/components/ContentChatList.tsx
  src/pages/Chat/ChatContent/components/ContentHeader.tsx
  src/pages/Chat/ChatContent/components/ContentInput.tsx
  src/pages/Chat/ChatContent/components/MobileHeader.tsx
  src/pages/Chat/ChatList/ChatList.tsx
  src/pages/Chat/ChatList/ChatListItem.tsx
  src/pages/index.ts
  src/routes/router.tsx
  src/services/chat/api.ts
  src/services/chat/query.ts
  src/services/chat/type.ts
Labels: :sparkles: feat

#74 지도 페이지에 채팅 연결
  package.json
  src/pages/Chat/Chat.tsx
  src/pages/Chat/ChatContent/ChatContents.tsx
  src/pages/Chat/ChatContent/components/ContentChatList.tsx
  src/pages/Chat/ChatContent/components/ContentHeader.tsx
  src/pages/Chat/ChatContent/components/ContentInput.tsx
  src/pages/Chat/ChatContent/components/MobileHeader.tsx
  src/pages/Chat/ChatList/ChatListItem.tsx
  src/pages/Map/components/MapGardenDetailBottomSection.tsx
  src/routes/router.tsx
  src/services/chat/api.ts
Labels: :sparkles: feat, :lipstick: style
